### ISSUE TITLE
Provide type definitions

### ISSUE THREAD

**Issue by remi2j** [hinok/react-router-last-location#11]
This repo has no `.d.ts` to provide better Typescript support. Definitely Typed doesn't have one either, so it would be nice if it was included in the project.

This isn't only useful for Typescript, it's also used by many IDEs to provide autocomplete suggestions and improve the experience.

**Comment by hinok** [comment]
Hey @remi2j 
I'm migrating this package to TypeScript so it should be available soon with typings.

**Comment by remi2j** [comment]
Nice! This and hooks support are great features, looking forward to the next release.

**Comment by hinok** [comment]
@remi2j If you'd like to try new version with types definitions, please install

```bash
npm install react-router-last-location@2.0.0-beta.1
```

Demo on CodeSandbox - https://codesandbox.io/s/zn208l91zp
