### ISSUE TITLE
ReferenceError: window is not defined in Server side rendering

### ISSUE THREAD

**Issue by sasiganth** [hinok/react-router-last-location#21]
Hi
      Using the library, When try to build the application, which has both server side rendering as well as client side rendering, got the following issue.

...\node_modules\react-router-last-location\dist\index.js:10
[1] })(window, function(__WEBPACK_EXTERNAL_MODULE__0__, __WEBPACK_EXTERNAL_MODULE__1__, __WEBPACK_EXTERNAL_MODULE__6__) {
[1]    ^
[1] ReferenceError: window is not defined

Kindly add the following check in index.js => `typeof window != "undefined" ? window : ''`

So that it will work without any issues in ssr based application.

**Comment by hinok** [comment]
Hey @sasiganth 
It's caused by UMD, will fix it soon. Thanks for reporting!

I'm using this library also in SSR based project but it's locked on `v1.1.0`.
If you don't need `hooks` or `typescript` support, consider for now using `v1.1.0` which works for 100% with SSR.

**Comment by sasiganth** [comment]
Hey @hinok 
I'm using it in `typescript` project with `hook` also, May I know how long it will take to fix?

**Comment by hinok** [comment]
I will release fixed version today evening.

**Comment by hinok** [comment]
@sasiganth Please upgrade to `2.0.0-beta.3`, it should fix the problem.

**Comment by sasiganth** [comment]
@hinok Have verified, now it's working fine. Thanks for the immediate fix.
