### ISSUE TITLE
Compatible with react-router-dom 5.x.x?

### ISSUE THREAD

**Issue by geotrev** [hinok/react-router-last-location#25]
I just upgraded one of my projects from React Router DOM 4.x.x to 5.x.x, and it appears the peerDependency specified by this package needs 4.x.x - just curious if there's been any effort in testing the compatibility there?

**Comment by hinok** [comment]
Hey @geotrev 
It should work because 5.x.x is backward compatible (https://reacttraining.com/blog/react-router-v5/)

> v5 is fully backwards compatible with 4.x
> The only reason for the major version bump has to do with how we were specifying dependencies in react-router-dom

I'll do some testing later today, will check if unit tests pass and bump peerDeps if everything will be okay.

**Comment by hinok** [comment]
@geotrev Published `v2.0.0-beta.4` that bumps `peerDependencies`. I'm closing this issue.
