### ISSUE TITLE
Support React 17+

### ISSUE THREAD

**Issue by fwolff** [hinok/react-router-last-location#46]
Hi,

It would be nice to support React 17+.
```
  "peerDependencies": {
    "prop-types": "^15.6.0",
    "react": "^15.5.4 || ^16.0.0 || ^17.0.0",
    "react-dom": "^15.5.4 || ^16.0.0 || ^17.0.0",
    "react-router-dom": "^4.1.1 || ^5.0.1"
  },
```

Thanks.

**Comment by benjih** [comment]
I just had a quick attempt at performing this change to support React 17 and the first issue I came across is that enzyme does not support React 17 yet. Once this is merged in (https://github.com/enzymejs/enzyme/pull/2430) and they've released, more than happy to take another look at this if no one else beats me to it.
