### ISSUE TITLE
Warning: <BrowserRouter> ignores the history prop

### ISSUE THREAD

**Issue by entozoon** [hinok/react-router-last-location#53]
This annoying warning is popping up, with react `17.0.2` and react-router-dom `5.2.0`
It all works fine, and is a great little package but yeah, any ideas of a workaround to get rid of the warning?

Typically this is what I'm working with:
```js
import { BrowserRouter, Route } from "react-router-dom";
import { LastLocationProvider } from "react-router-last-location";
 <BrowserRouter>
  <LastLocationProvider>
    <Route>
      ...
```

I've tried this, as some people have suggested, but it's the same result unfortunately:
```js
import { BrowserRouter, Route } from "react-router-dom";
import { LastLocationProvider } from "react-router-last-location";
import { createBrowserHistory } from "history";
const history = createBrowserHistory();
 <BrowserRouter history={history}>
  <LastLocationProvider>
    <Route>
      ...
```

Perhaps it's just something that'll be fixed in [due course](https://github.com/hinok/react-router-last-location/issues/46) or even some issue with react-router-dom? Who knows, but a cheeky workaround would be handy

**Comment by hinok** [comment]
@entozoon Hey 👋, can you prepare a small reproduction demo on codesandbox?
I'd really speed up resolving the issue on my side.

**Comment by entozoon** [comment]
Oh dude @hinok , I'm so sorry. My issue was with another package! 
react-delay-link (and it's not the first time I've had PRs out to fix that package).

I can only apologise, and thank you for the codesandbox tip - it helped me get to the root of the problem!

**Comment by hinok** [comment]
@entozoon I'm glad that I was even able to help 😅
