### ISSUE TITLE
Converting the tests from Enzyme to Testing Library.

### ISSUE THREAD

**Issue by tigerabrodi** [hinok/react-router-last-location#54]
Hi :wave:

I recognized your library when looking for a solution that allows me to check the previous pathname. :grin: 

I saw that you guys are currently using Enzyme, which itself seems to be [blocking the support of React 17+.](https://github.com/hinok/react-router-last-location/issues/46)

I and many friends are a part of the Open Source Raid Guild, a group that supports OSS projects. :blue_heart: 

Many of us work together on one large PR. :nerd_face: 

We would fork your project to our Github Team and work on our fork, and communicate with some of the maintainers closely over at Discord.

Read more about us: https://github.com/OpenSourceRaidGuild/tutorial-quest#hi-wave-welcome-to-the-open-source-raid-guild-crossed_swords

Our discord server: https://discord.gg/JczjG8su

Let us know if you've any questions, and feel free to join the Discord already, even if it is just a question. :partying_face:

**Comment by joealden** [comment]
@hinok FYI this would unblock #46.

**Comment by hinok** [comment]
@joealden  @tigerabrodi Feel free to create a PR here that will use `react-testing-library` instead of `enzyme`.

**Comment by JacobMGEvans** [comment]
We will create a PR soon. 

Any objections to adding more tests as well?

**Comment by JacobMGEvans** [comment]
@hinok Nearly done.

**Comment by JacobMGEvans** [comment]
Should have something by this weekend.
