### ISSUE TITLE
Update peerDependencies react-router-dom to v6

### ISSUE THREAD

**Issue by Cyberhan123** [hinok/react-router-last-location#67]
Do everyone have any suggestions?

**Comment by joealden** [comment]
I believe `Redirect` was removed from v6, so I think it'd be more involved than just updating the peer dep version.

**Comment by Cyberhan123** [comment]
`Redirect` not been removed

**Comment by joealden** [comment]
Although it isn't expicitly mentioned as a step in the migraton guide for v4/v5, that migration guide says that `Navigate` replaces `Redirect`, and its behaviour is slightly different.

**Comment by Cyberhan123** [comment]
yes, you are right.
